In [1]:
#Write a NumPy program to test element-wise for NaN of a given array.

import numpy as np

a=np.array([1,0,np.nan,np.inf])

print('Origional Array:',a)
print('Test ele wise for NaN:',np.isnan(a))

Origional Array: [ 1.  0. nan inf]
Test ele wise for NaN: [False False  True False]


In [3]:
#Write a NumPy program to create an array with values ranging from 12 to 38..

x=np.arange(12,38)
print(x)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


In [4]:
#Write a NumPy program to reverse an array (first element becomes last).

x=np.arange(10,21)
print("origional array:",x)
x=x[::-1]
print('reverse array:=',x)

origional array: [10 11 12 13 14 15 16 17 18 19 20]
reverse array:= [20 19 18 17 16 15 14 13 12 11 10]


In [5]:
#Write a NumPy program to convert an array to a float type. 

arr=np.ones(4,dtype='float')
print(arr)

[1. 1. 1. 1.]


In [13]:
#Write a NumPy program to create a 2d array with 1 on the border and 0 inside.


x=np.ones((5,5),dtype='int')
print('Origional array:')
#print()
print(x)
print('1 on border and 0 inside in arr:=')
print()
x[1:-1,1:-1]=0
print(x)

Origional array:
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
1 on border and 0 inside in arr:=

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [15]:
#Write a NumPy program to append values to the end of an array.

x=[1,2,3,4,5]
print('origional array:=',x)
x=np.append(x,[[6,7,8,9,10],[11,12,13,14,15]])
print('after appending:',x)

origional array:= [1, 2, 3, 4, 5]
after appending: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [19]:
#Write a NumPy program to test whether each element of a 1-D array is also present in a second array.

array1=np.array([0,1,2,4,6])
print('array1',array1)
array2=[0,6]
print('array2:',array2)
print('compare each ele of array1 and array2:==')

print(np.in1d(array1,array2))

array1 [0 1 2 4 6]
array2: [0, 6]
compare each ele of array1 and array2:==
[ True False False False  True]


In [21]:
#Write a NumPy program to get the unique elements of an array. 

x=np.array([10,10,20,20,30,30])
print('Origional array:',x)
print('unique ele of 1d array:',np.unique(x))



Origional array: [10 10 20 20 30 30]
unique ele of 1d array: [10 20 30]


In [22]:
x=np.array([[1,1],[2,3]])
print('origional array:')
print(x)
print('unique ele of 2d array:',np.unique(x))

origional array:
[[1 1]
 [2 3]]
unique ele of 2d array: [1 2 3]


In [24]:
#Write a NumPy program to find the indices of the maximum and minimum values along the given axis of an array.

x=np.array([0,1,2,3,4,5,6])
print('Origional array:',x)
print('Maximun values:=',np.argmax(x))
print('Minimum values:',np.argmin(x))

Origional array: [0 1 2 3 4 5 6]
Maximun values:= 6
Minimum values: 0


In [26]:
#Write a NumPy program to create a contiguous flattened array

x=np.array([[10,20,30],[20,40,50]])
print('Origional array:')
print(x)
y=np.ravel(x)
print('new flattened arrau:',y)
print(y)

Origional array:
[[10 20 30]
 [20 40 50]]
new flattened arrau: [10 20 30 20 40 50]
[10 20 30 20 40 50]


In [28]:
#Write a NumPy program to concatenate two 2-dimensional arrays. 

arr1=np.arange(1,10).reshape(3,3)
arr2=np.arange(10,19).reshape(3,3)
print('Array 1:=')
print(arr1)
print('Array 2:=')
print(arr2)

Array 1:=
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Array 2:=
[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [31]:
#Write a NumPy program to convert 1-D arrays as columns into a 2-D array. 

arr=np.array([10,20,30,40,50,60,70,80])
print('before reshaping:',arr)
arr2=arr.reshape(2,4)
print('After reshaping having diamension 2*4:')
print(arr2)

before reshaping: [10 20 30 40 50 60 70 80]
After reshaping having diamension 2*4:
[[10 20 30 40]
 [50 60 70 80]]


In [32]:
#Write a NumPy program (using NumPy) to sum of all the multiples of 3 or 5 below 100. 

x=np.arange(1,100)
n=x[(x%3==0)|(x%5==0)]
print(n[:100])
print('sum:',n.sum())

[ 3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51
 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]
sum: 2318


In [33]:
#Write a NumPy program to get the index of a maximum element in a NumPy array along one 
#axis

a=np.array([[1,2,3],[4,3,1]])
print('Origional array:=')
print(a)
i,j=np.unravel_index(a.argmax(),a.shape)
print('index of a maximum ele in a numpy array along one axis:')
print(a[i,j])


Origional array:=
[[1 2 3]
 [4 3 1]]
index of a maximum ele in a numpy array along one axis:
4


In [34]:
#Write a NumPy program to stack 1-D arrays as row wise. 

print('Origional aray:=')
x=np.array((1,2,3))
y=np.array((2,3,4))
print("Array-1:",x)
print("Array-2:",y)
new_array=np.row_stack((x,y))
print('stack 1-d arrays as rows wise:')
print(new_array)

Origional aray:=
Array-1: [1 2 3]
Array-2: [2 3 4]
stack 1-d arrays as rows wise:
[[1 2 3]
 [2 3 4]]


In [35]:
#Write a NumPy program to stack 1-D arrays as col wise. 

print('Origional aray:=')
x=np.array((1,2,3))
y=np.array((2,3,4))
print("Array-1:",x)
print("Array-2:",y)
new_array=np.column_stack((x,y))
print('stack 1-d arrays as col wise:')
print(new_array)

Origional aray:=
Array-1: [1 2 3]
Array-2: [2 3 4]
stack 1-d arrays as col wise:
[[1 2]
 [2 3]
 [3 4]]


In [36]:
#Write a NumPy program to get the minimum and maximum value of a given array along the second axis. 

arr=np.array([[0,1],[2,3]])
print("given array:")
print(arr)
r1=np.amax(arr,1)
print('Maximum value:',r1)

r2=np.amin(arr,1)
print("Minimum value:",r2)

given array:
[[0 1]
 [2 3]]
Maximum value: [1 3]
Minimum value: [0 2]


In [50]:
#Write a NumPy program to replace odd number in 2d array by its square 
def fun_list(list_, x):
    s=[]    
    s= [i**x for i in list_ if (i%2)!=0]
    list_=s          
    print(list_)
list1 = [1, 2, 3, 4,5,6,7]
list2 = [2, 3, 4, 5,5,6,7]
print(fun_list(list1, 2))
print(fun_list(list2, 3))  

[1, 9, 25, 49]
None
[27, 125, 125, 343]
None


In [46]:
#Write a NumPy program to create a 3x3x3 array with random values. 
x = np.random.random((3,3,3))
print(x)

[[[0.19818754 0.08799622 0.22026988]
  [0.76124045 0.77219442 0.80423108]
  [0.63843909 0.62483732 0.87825244]]

 [[0.18906955 0.41435582 0.57529677]
  [0.44220522 0.67460711 0.92356771]
  [0.24989181 0.99236591 0.4464311 ]]

 [[0.05430147 0.61259114 0.92614094]
  [0.90371857 0.68040585 0.50378952]
  [0.8741519  0.82471925 0.03554491]]]


In [48]:
# Write a NumPy program to calculate the absolute value element-wise. 
x = np.array([-10.2, -122.2, .20])
print("Original array:")
print(x)
print("Element-wise absolute value:")
print(np.absolute(x))

Original array:
[ -10.2 -122.2    0.2]
Element-wise absolute value:
[ 10.2 122.2   0.2]
